//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapcomMusicDisassembler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapcomMusicDisassembler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capcom Music Engine Tool.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch file used to compile the code does not exist..
        /// </summary>
        internal static string AssemblerFileNotExist {
            get {
                return ResourceManager.GetString("AssemblerFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca65.exe.
        /// </summary>
        internal static string CompilerExe {
            get {
                return ResourceManager.GetString("CompilerExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ld65.exe.
        /// </summary>
        internal static string LinkerExe {
            get {
                return ResourceManager.GetString("LinkerExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to music.prg.
        /// </summary>
        internal static string MusicPRG {
            get {
                return ResourceManager.GetString("MusicPRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Track.
        /// </summary>
        internal static string MusicTrack {
            get {
                return ResourceManager.GetString("MusicTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Track Disassembly.
        /// </summary>
        internal static string MusicTrackDisassembly {
            get {
                return ResourceManager.GetString("MusicTrackDisassembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .nes.
        /// </summary>
        internal static string NESFileExtension {
            get {
                return ResourceManager.GetString("NESFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The music.prg is not present. WHY?!?.
        /// </summary>
        internal static string NoOutputFile {
            get {
                return ResourceManager.GetString("NoOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified ROM does not exist..
        /// </summary>
        internal static string ROMNotExist {
            get {
                return ResourceManager.GetString("ROMNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a game..
        /// </summary>
        internal static string SelectGame {
            get {
                return ResourceManager.GetString("SelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Effect.
        /// </summary>
        internal static string SoundEffect {
            get {
                return ResourceManager.GetString("SoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music tracks disassembled..
        /// </summary>
        internal static string TracksDisassembled {
            get {
                return ResourceManager.GetString("TracksDisassembled", resourceCulture);
            }
        }
    }
}
